Should also unlock on draft status
getsentry/tacos-gha pull request #251
Opened 2024-08-14 22:35 UTC by kneeyo1

2024-08-14 22:37 UTC, bukzor approved these changes
_technically_ there should be a failing test to match this change

2024-08-14 22:39 UTC, lynnagara requested changes
I don't think DRAFT is a state in github

2024-08-14 22:41 UTC, bukzor commented on lib/tf_lock/tf_lock_acquire.py
> +    return status in ("CLOSED", "MERGED", "DRAFT")
It's not that simple, unfortunately:

```suggestion
def is_pr_unlockable(gh_url: str) -> bool:
    status = sh.json(
        ("gh", "pr", "view", gh_url, "--json", "state,isDraft")
    )
    ...
```

2024-08-15 16:56 UTC, kneeyo1 commented on spec/scenarios/orphaned_lock.py
> +        assert pr2.check("Terraform Plan").wait().success
ah didn't catch that, thanks

2024-08-15 17:03 UTC, lynnagara approved these changes

2024-08-15 19:00 UTC, merged